name:  model_map
version: 0.2.6
description:  Mirror based model mapping
author: Dan Parnham <dan@teadriven.me.uk>
homepage: http://github.com/parnham/model_map.dart

environment:
  sdk: ">=0.8.10+6 <2.0.0"

dev_dependencies:
  unittest: any
